name: 'Lint Markdown Files'

on:
  pull_request:
    branches: [main]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files: 'content/**/*.md'
          ignore: node_modules
